//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSecond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public int user_id { get; set; }
        public int avand_id { get; set; }
        public int bank_id { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Avand Avand { get; set; }
        public virtual Banks Banks { get; set; }
        public virtual Users Users { get; set; }
    }
}
